[package]
name = "fast-set"
version = "0.5.0"
edition = "2024"
publish = false

[dependencies]
intern = { git = "https://github.com/danylaporte/intern.git" }
once_cell = { version = "1", features = ["parking_lot"] }
rustc-hash = "2.1"

[dev-dependencies]
dhat = "0.3"
rand = "0.9"
